# Generated by Django 6.0.2 on 2026-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, to='discord.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='servers',
            field=models.ManyToManyField(blank=True, to='discord.servers'),
        ),
    ]
