# Generated by Django 6.0.2 on 2026-02-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_alter_users_friends_alter_users_servers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='title',
        ),
    ]
