# Generated by Django 6.0.2 on 2026-02-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_rename_name_users_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='title',
            new_name='name',
        ),
    ]
